name: Build on push

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: $ {{ secrets.NETLIFY_AUTH_TOKEN }}

        run: |
          yarn
          yarn test
          yarn build

