name: Build on push
on:
  push:
    paths-ignore:
      - ".github/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      run: |
          yarn
          yarn test
          yarn build
          yarn global add netlify-cli
          netlify deploy -p
