name: Build on push

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
jobs:
    deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1

      - name: Build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: $ {{ secrets.NETLIFY_AUTH_TOKEN }}

        run: |
          yarn
          yarn test
          yarn build

          npx netlify-cli deploy --dir=public --prod

